### ISSUE TITLE
 directory /var/cache/apt/archives/partial is missing

### ISSUE THREAD

**Issue by Elray02** [BelaPlatform/bela-image#15]
with this image of bela :" bela_image_v0.2.0a_stable_2016.10.24" , if i run "apt-get update"  it come out this :  

_E: Archives directory /var/cache/apt/archives/partial is missing. - Acquire (2: No such file or directory)_

i solved making : 
mkdir -p /var/cache/apt/archive/partial 

but i think is not normal right?

thanks

**Comment by giuliomoro** [comment]
oh ok thanks. I removed all the stuff in `/var/cache` to make the image smaller. Hope next time I will remember to re-create that folder.
