### ISSUE TITLE
debconf: DbDriver "config": mkdir :No such file or directory

### ISSUE THREAD

**Issue by Elray02** [BelaPlatform/bela-image#16]
Hello,hello 

each time i try to run _apt-get install_+ _some package name_   i get this error

_debconf: DbDriver "config": mkdir :No such file or directory_

there are some hint for solve this?

i'm using the last img for bela

thanks again for the help

**Comment by giuliomoro** [comment]
good looks like I screwed up in more than one place. Let me have a look.

**Comment by giuliomoro** [comment]
alright, but the installation still goes through succesfully, right?
this should be enough:

```
mkdir -p /var/cache/debconf
```
