### ISSUE TITLE
Add pasm to image

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/bela-image#5]
pasm is part of the am335x prussdrv package. It compiles PRU assembly files into binaries. It would be useful to have this (and by extension the PRU C compiler) on the board so projects using the second PRU could be edited without installing special tools.

**Comment by LBDonovan** [comment]
I agree this would be useful. It would probably be possible to add a rule for compiling PRU code to the Makefile, so that you could use the IDE / scripts to develop for the PRU with the normal workflow, which could be very powerful.

**Comment by apmcpherson** [comment]
Agreed. If you do this in the Makefile, pasm needs to be the first thing to run because it creates a .h file which affects the dependencies.
